# dbt_project.yml

name: 'secureguard_dbt'
version: '1.0.0'
config-version: 2

# Esta configuração define qual "profile" o dbt usará para este projeto.
profile: 'secureguard_dbt'

# Estas configurações especificam onde o dbt deve procurar por diferentes tipos de arquivos.
# A configuração `model-paths`, por exemplo, indica que os modelos neste projeto podem ser
# encontrados no diretório "models/". Você provavelmente não precisará alterar isso!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # diretórios a serem removidos pelo `dbt clean`
  - "target"
  - "dbt_packages"


# Configurando modelos
# Documentação completa: https://docs.getdbt.com/docs/configuring-models

# Nesta configuração de exemplo, dizemos ao dbt para construir todos os modelos no diretório
# example/ como tabelas. Essas configurações podem ser sobrescritas nos arquivos de modelo
# individuais usando a macro `{{ config(...) }}`.
models:
  secureguard_dbt:
    # A configuração indicada por + se aplica a todos os arquivos dentro de models/
    +materialized: view
    silver:
      +materialized: table
      +tags: "silver"
    gold:
      +materialized: view
      +tags: "gold"

vars:
  # A variável `PII_SALT_SECRET` deve ser injetada pelo pipeline de CI/CD
  # Para desenvolvimento local, você pode defini-la no seu profiles.yml
  # ou via linha de comando: dbt run --vars '{"PII_SALT_SECRET": "seu-segredo-local"}'
  PII_SALT_SECRET: "{{ env_var('DBT_PII_SALT_SECRET', 'default-dev-salt') }}"
