version: 2

sources:
  - name: raw_lakehouse_data
    description: "Dados de origem ingeridos na camada Bronze do lakehouse."
    # Para o BigQuery, o banco de dados (database) é o ID do projeto GCP.
    # Podemos usar uma variável para tornar isso dinâmico.
    database: "{{ var('gcp_project_id') }}"
    schema: "bronze" # Deve corresponder ao nome do dataset no BigQuery
    tables:
      - name: transactions_raw
        description: "Tabela de transações brutas carregada do GCS."
        # Em um cenário real, você configuraria testes de frescor (freshness) aqui.
        # loaded_at_field: _loaded_at_timestamp
        # freshness:
        #   warn_after: {count: 12, period: hour}
        #   error_after: {count: 24, period: hour}
